name: .NET Core App CI to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        Username: ${{ secrets.DOCKER_HUB_USERNAME }}
        Password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./
        file: ./src/azure.devops.notify.dingtalk.robots/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/devops.to.dingtalk.robots:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
